name: JobsBoard
version: ${project.version}
main: me.rebelmythik.jobsboard.JobsBoardMain
api-version: 1.16
depend: [ Vault, Essentials ]
authors: [ RebelMythik, Kronus ]
description: Job Board!
commands:
  jb:
    aliases:
      - jobsboard
    description: Main command for working with the Jobs Board plugin
    permission: jobsboard.use
permissions:
  jobsboard.*:
    description: All jobsboard permissions
    default: op
    children:
      jobsboard.command.*: true
  jobsboard.command.*:
    description: All commands
    default: op
    children:
      jobsboard.command.browse: true
      jobsboard.command.createjob: true
  jobsboard.use:
    description: Permission to use the main jobsboard command /jb
    default: true
  jobsboard.command.browse:
    description: Allows the use of /jb browse
    default: true
  jobsboard.command.createjob:
    description: Allows the use of /jb create <item> <amount> <reward>
    default: true